### ISSUE TITLE
Data rate slowdown factor is not applied to the HSI config

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/minidaqapp#45]
The data rate slowdown factor never makes it into the clock frequency that's passed into the HSI configuration, which makes the HSI timestamp estimate get ahead of the "real" timestamp when a slowdown factor is applied.

**Comment by strilov** [comment]
Hi Phil,

Ah, this might explain issues which have been seen with the fake hsi generator. Pull request with fix here: https://github.com/DUNE-DAQ/minidaqapp/pull/46.

**Comment by philiprodrigues** [comment]
Fixed by #46
